Задания из темы "Объекты"
js-tasks-ru/jsbasic-20201022_svfeldman pull request #4
Opened 2020-10-28 15:21 UTC by svfeldman

2020-10-28 16:28 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать свойс��ва других типов
+ должна складывать все зарплаты
```
```diff
Создайте калькулятор
+ должно складывать числа
+ должно умножать числа
```
```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект с удалённым свойством - пустой
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-10-29 13:06 UTC, koalex requested changes
Исправь замечание

2020-10-29 13:06 UTC, koalex commented on 2-module/3-task/index.js
> +    x = a;
Оно конечно работает, но это неправильно. Суть этого задания в том чтобы создавать свойства объекта через `this`. То есть должно быть так:
```
read(a, b) {
  this.a = a;
  this.b = b;
}
sum() {
  return this.a + this.b;
}...
```

2020-10-29 13:48 UTC, svfeldman commented on 2-module/3-task/index.js
> +    x = a;
Поправил. Я так понимаю новый PR делать не нужно, Вы увидите исправления в этом PR, а я делаю только commit и push?

2020-10-29 14:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-10-30 11:55 UTC, koalex approved these changes
Теперь ОК

2020-10-30 11:55 UTC, merged